#!/bin/sh

set -eu

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
BASE_DIR="$(dirname "${SCRIPTS_DIR}")"
OUTPUT_DIR="${BASE_DIR}/lib"

if [ "$#" -gt 0 ]; then
  OUTPUT_DIR="$1"
fi

rm -vfR "${OUTPUT_DIR}"
mkdir -vp "${OUTPUT_DIR}"

cp -fR \
  "${BASE_DIR}/index.html" \
  "${BASE_DIR}/src" \
  "${BASE_DIR}/package.json" \
  "${BASE_DIR}/package-lock.json" \
  "${OUTPUT_DIR}/"

(
  cd "${OUTPUT_DIR}"
  npm install --omit dev
)
